on:
  workflow_dispatch:
  
jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete workflow runs
        uses: ./ # Uses an action in the root directory
        id: delete-workflow-runs
        with:
          repository: miwebhostingtry/delete-workflow-runs
          workflow: ".github/workflows/runme.yml"
          older-than-seconds: 60
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
          maximum-workflow-runs-to-keep: 1
          # what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
